
language: java

sudo: required

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository/
    - $HOME/.pip/repository/

# It was fixed by downgrading aws-cli and python27-botocore:
# python27-botocore-1.8.13-1.66.amzn1.noarch.rpm
# aws-cli-1.14.9-1.48.amzn1.noarch.rpm
# 1.16.1

before_install:
  - mkdir -p $HOME/.pip/repository/
  - pip install --cache-dir $HOME/.pip/repository/ --user awscli==1.14.9
  - pip install --cache-dir $HOME/.pip/repository/ --user aws-sam-cli==0.5.0
  - export PATH=$PATH:$HOME/.local/bin

script:
  -  mvn -e verify deploy
  - ./deploy.sh