
language: java

sudo: required

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository/

install:
  - echo installing..

script:
#  -  mvn -e verify deploy
  -  mvn -DskipTests clean install
  -  depoy_function.sh cfp-status-function