
language: java

sudo: required

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository/

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

script:
  -  mvn -e verify deploy
  - ./deploy_function.sh cfp-status-function