
language: java

sudo: required

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository/
    - $HOME/.pip/repository/

before_install:
  - mkdir -p $HOME/.pip/repository/
  - pip install --cache-dir $HOME/.pip/repository/ --user awscli==1.16.1
  - pip install --cache-dir $HOME/.pip/repository/ --user aws-sam-cli==0.5.0
  - export PATH=$PATH:$HOME/.local/bin

script:
  -  mvn -e verify deploy
  - ./deploy.sh