
language: java

sudo: required

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository/

before_install:
  - pip install --user awscli==1.16.1
  - pip install --user aws-sam-cli==0.5.0
  - export PATH=$PATH:$HOME/.local/bin

script:
  -  mvn -e verify deploy
  - ./deploy.sh